version: '3.7'

services:
  drupal:
    image: drupal:8
    environment:
      HOME: /var/www/home
    volumes:
      - ./docroot:/var/www/html
      - ./volumes/home:/var/www/home
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal8
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql

  mailserver:
    image: mailhog/mailhog
    depends_on:
      - drupal
