version: '3.7'

services:
  drupal:
    image: servinube/drupal:8.5-dev
    environment:
      HOME: /var/www/home
    volumes:
      - ./docroot:/var/www/web
      - ./volumes/home:/var/www/home
      - ./volumes/ssmtp.conf:/etc/ssmtp/ssmtp.conf
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal8
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql

  mailcatcher:
    image: mailhog/mailhog
    ports:
      - "8082:8025"
    depends_on:
      - drupal
